### ISSUE TITLE
Conflicting requirements during installation leading to failed build

### ISSUE THREAD

**Issue by zippyzoo77** [MIT-SPARK/Kimera-Multi#11]
Hello,

I am trying to install kimera multi, my machine is running ubuntu 20.04, with ros noetic, and I have an issue I cannot work out with installing it. I've posted the errors at the end of the post, but the problem seems to be that two of the dependencies on the package are not compatible: the pcl libraries (installed with sudo apt-get install ros-noetic-pcl-ros during the installation steps) and the libvtk6-dev package (also installed the same way during installation steps) cannot be on the machine at the same time, installing one removes the other. How can I work around this and get kimera-multi to work? 

Thanks,
Marina

Errors with libvtk6-dev installed:
```
---------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/user/uuv_ws/devel:/opt/ros/noetic
Workspace:                   /home/user/kimera_ws
---------------------------------------------------------------------------------
Build Space:        [exists] /home/user/kimera_ws/build
Devel Space:        [exists] /home/user/kimera_ws/devel
Install Space:      [unused] /home/user/kimera_ws/install
Log Space:          [exists] /home/user/kimera_ws/logs
Source Space:       [exists] /home/user/kimera_ws/src
DESTDIR:            [unused] None
---------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
---------------------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTSAM_TANGENT_PREINTEGRATION=OFF -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DOPENGV_BUILD_WITH_MARCH_NATIVE=OFF
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
---------------------------------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
---------------------------------------------------------------------------------
Workspace configuration appears valid.
---------------------------------------------------------------------------------
[build] Found 45 packages in 0.0 seconds.                                       
[build] Package table is up to date.                                            
Starting  >>> catkin_boost_python_buildtool                                     
Starting  >>> catkin_simple                                                     
Starting  >>> dpgo                                                              
Starting  >>> gtsam                                                             
Starting  >>> hdf5_map_io                                                       
Starting  >>> image_undistort                                                   
Starting  >>> kimera_multi                                                      
Starting  >>> mesh_msgs                                                         
Starting  >>> pybind11_catkin                                                   
Finished  <<< catkin_simple                                     [ 0.2 seconds ] 
Starting  >>> cmake_external_project_catkin                                     
Starting  >>> eigen_catkin                                                      
Starting  >>> gflags_catkin                                                     
Starting  >>> kimera_rviz_markers                                               
Starting  >>> mesh_rviz_plugins                                                 
Starting  >>> opencv3_catkin                                                    
Starting  >>> pose_graph_tools                                                  
Starting  >>> protobuf_catkin                                                   
Finished  <<< hdf5_map_io                                       [ 0.2 seconds ] 
Starting  >>> voxblox_msgs                                                      
Finished  <<< catkin_boost_python_buildtool                     [ 0.1 seconds ] 
Finished  <<< kimera_multi                                      [ 0.1 seconds ] 
Finished  <<< pybind11_catkin                                   [ 0.1 seconds ] 
Finished  <<< protobuf_catkin                                   [ 0.1 seconds ] 
________________________________________________________________________________
Errors     << image_undistort:cmake /home/user/kimera_ws/logs/image_undistort/build.cmake.001.log
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "pcl_ros" with any
  of the following names:

    pcl_rosConfig.cmake
    pcl_ros-config.cmake

  Add the installation prefix of "pcl_ros" to CMAKE_PREFIX_PATH or set
  "pcl_ros_DIR" to a directory containing one of the above files.  If
  "pcl_ros" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)


cd /home/user/kimera_ws/build/image_undistort; catkin build --get-env image_undistort | catkin env -si  /usr/bin/cmake /home/user/kimera_ws/src/image_undistort --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/user/kimera_ws/devel/.private/image_undistort -DCMAKE_INSTALL_PREFIX=/home/user/kimera_ws/install -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTSAM_TANGENT_PREINTEGRATION=OFF -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DOPENGV_BUILD_WITH_MARCH_NATIVE=OFF; cd -

................................................................................
Failed     << image_undistort:cmake                             [ Exited with code 1 ]
Failed    <<< image_undistort                                   [ 0.4 seconds ] 
Abandoned <<< catkin_boost_python_buildtool_test                [ Unrelated job failed ]
Abandoned <<< glog_catkin                                       [ Unrelated job failed ]
Abandoned <<< eigen_checks                                      [ Unrelated job failed ]
Abandoned <<< kimera_rpgo                                       [ Unrelated job failed ]
Abandoned <<< label_manager                                     [ Unrelated job failed ]
Abandoned <<< mesh_msgs_hdf5                                    [ Unrelated job failed ]
Abandoned <<< mesh_msgs_transform                               [ Unrelated job failed ]
Abandoned <<< mesh_tools                                        [ Unrelated job failed ]
Abandoned <<< minkindr                                          [ Unrelated job failed ]
Abandoned <<< minkindr_conversions                              [ Unrelated job failed ]
Abandoned <<< numpy_eigen                                       [ Unrelated job failed ]
Abandoned <<< minkindr_python                                   [ Unrelated job failed ]
Abandoned <<< dbow2_catkin                                      [ Unrelated job failed ]
Abandoned <<< opengv_catkin                                     [ Unrelated job failed ]
Abandoned <<< kimera_vio                                        [ Unrelated job failed ]
Abandoned <<< dpgo_ros                                          [ Unrelated job failed ]
Abandoned <<< kimera_multi_lcd                                  [ Unrelated job failed ]
Abandoned <<< kimera_distributed                                [ Unrelated job failed ]
Abandoned <<< kimera_vio_ros                                    [ Unrelated job failed ]
Abandoned <<< rviz_map_plugin                                   [ Unrelated job failed ]
Abandoned <<< rviz_mesh_plugin                                  [ Unrelated job failed ]
Abandoned <<< voxblox                                           [ Unrelated job failed ]
Abandoned <<< kimera_semantics                                  [ Unrelated job failed ]
Abandoned <<< kimera_pgmo                                       [ Unrelated job failed ]
Abandoned <<< voxblox_rviz_plugin                               [ Unrelated job failed ]
Abandoned <<< voxblox_ros                                       [ Unrelated job failed ]
Abandoned <<< kimera_semantics_ros                              [ Unrelated job failed ]
Finished  <<< cmake_external_project_catkin                     [ 0.1 seconds ] 
Finished  <<< mesh_msgs                                         [ 0.7 seconds ] 
Finished  <<< opencv3_catkin                                    [ 0.2 seconds ] 
Finished  <<< gflags_catkin                                     [ 0.1 seconds ] 
Finished  <<< eigen_catkin                                      [ 0.1 seconds ] 
Finished  <<< pose_graph_tools                                  [ 0.4 seconds ] 
Finished  <<< kimera_rviz_markers                               [ 0.3 seconds ] 
Finished  <<< voxblox_msgs                                      [ 0.2 seconds ] 
Finished  <<< dpgo                                              [ 0.5 seconds ] 
________________________________________________________________________________
Errors     << mesh_rviz_plugins:cmake /home/user/kimera_ws/logs/mesh_rviz_plugins/build.cmake.001.log
CMake Error at /home/user/kimera_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package):
  By not providing "Findpcl_ros.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pcl_ros", but
  CMake did not find one.

  Could not find a package configuration file provided by "pcl_ros" with any
  of the following names:

    pcl_rosConfig.cmake
    pcl_ros-config.cmake

  Add the installation prefix of "pcl_ros" to CMAKE_PREFIX_PATH or set
  "pcl_ros_DIR" to a directory containing one of the above files.  If
  "pcl_ros" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:5 (catkin_simple)


cd /home/user/kimera_ws/build/mesh_rviz_plugins; catkin build --get-env mesh_rviz_plugins | catkin env -si  /usr/bin/cmake /home/user/kimera_ws/src/mesh_rviz_plugins --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/user/kimera_ws/devel/.private/mesh_rviz_plugins -DCMAKE_INSTALL_PREFIX=/home/user/kimera_ws/install -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTSAM_TANGENT_PREINTEGRATION=OFF -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DOPENGV_BUILD_WITH_MARCH_NATIVE=OFF; cd -

................................................................................
Failed     << mesh_rviz_plugins:cmake                           [ Exited with code 1 ]
Failed    <<< mesh_rviz_plugins                                 [ 0.5 seconds ] 
Finished  <<< gtsam                                             [ 4.2 seconds ] 
[build] Summary: 16 of 45 packages succeeded.                                   
[build]   Ignored:   None.                                                      
[build]   Warnings:  None.                                                      
[build]   Abandoned: 27 packages were abandoned.                                
[build]   Failed:    2 packages failed.        

 ```

Erros with pcl installed:

```

---------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/user/uuv_ws/devel:/opt/ros/noetic
Workspace:                   /home/user/kimera_ws
---------------------------------------------------------------------------------
Build Space:        [exists] /home/user/kimera_ws/build
Devel Space:        [exists] /home/user/kimera_ws/devel
Install Space:      [unused] /home/user/kimera_ws/install
Log Space:          [exists] /home/user/kimera_ws/logs
Source Space:       [exists] /home/user/kimera_ws/src
DESTDIR:            [unused] None
---------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
---------------------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTSAM_TANGENT_PREINTEGRATION=OFF -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DOPENGV_BUILD_WITH_MARCH_NATIVE=OFF
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
---------------------------------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
---------------------------------------------------------------------------------
Workspace configuration appears valid.
---------------------------------------------------------------------------------
[build] Found 45 packages in 0.0 seconds.                                       
[build] Package table is up to date.                                            
Starting  >>> catkin_boost_python_buildtool                                     
Starting  >>> catkin_simple                                                     
Starting  >>> dpgo                                                              
Starting  >>> gtsam                                                             
Starting  >>> hdf5_map_io                                                       
Starting  >>> image_undistort                                                   
Starting  >>> kimera_multi                                                      
Starting  >>> mesh_msgs                                                         
Starting  >>> pybind11_catkin                                                   
Finished  <<< catkin_boost_python_buildtool                     [ 0.2 seconds ] 
Finished  <<< hdf5_map_io                                       [ 0.2 seconds ] 
Finished  <<< kimera_multi                                      [ 0.1 seconds ] 
Finished  <<< image_undistort                                   [ 0.4 seconds ] 
Finished  <<< pybind11_catkin                                   [ 0.2 seconds ] 
Finished  <<< catkin_simple                                     [ 0.1 seconds ] 
Starting  >>> catkin_boost_python_buildtool_test                                
Starting  >>> cmake_external_project_catkin                                     
Starting  >>> eigen_catkin                                                      
Starting  >>> gflags_catkin                                                     
Starting  >>> kimera_rviz_markers                                               
Starting  >>> mesh_rviz_plugins                                                 
Starting  >>> opencv3_catkin                                                    
Starting  >>> pose_graph_tools                                                  
Starting  >>> protobuf_catkin                                                   
Starting  >>> voxblox_msgs                                                      
Finished  <<< mesh_msgs                                         [ 0.3 seconds ] 
Starting  >>> label_manager                                                     
Starting  >>> mesh_msgs_transform                                               
Starting  >>> rviz_map_plugin                                                   
Starting  >>> rviz_mesh_plugin                                                  
Finished  <<< dpgo                                              [ 0.8 seconds ] 
Finished  <<< protobuf_catkin                                   [ 0.1 seconds ] 
Finished  <<< gflags_catkin                                     [ 0.1 seconds ] 
Finished  <<< voxblox_msgs                                      [ 0.4 seconds ] 
Finished  <<< catkin_boost_python_buildtool_test                [ 0.1 seconds ] 
Finished  <<< kimera_rviz_markers                               [ 0.5 seconds ] 
Finished  <<< eigen_catkin                                      [ 0.1 seconds ] 
Finished  <<< opencv3_catkin                                    [ 0.2 seconds ] 
Finished  <<< cmake_external_project_catkin                     [ 0.1 seconds ] 
Finished  <<< pose_graph_tools                                  [ 0.5 seconds ] 
Finished  <<< mesh_rviz_plugins                                 [ 0.6 seconds ] 
Finished  <<< rviz_mesh_plugin                                  [ 0.4 seconds ] 
Starting  >>> glog_catkin                                                       
Finished  <<< label_manager                                     [ 0.5 seconds ] 
Starting  >>> mesh_msgs_hdf5                                                    
Starting  >>> numpy_eigen                                                       
Starting  >>> dbow2_catkin                                                      
Starting  >>> dpgo_ros                                                          
Finished  <<< mesh_msgs_transform                               [ 0.4 seconds ] 
Finished  <<< gtsam                                             [ 3.1 seconds ] 
Starting  >>> kimera_rpgo                                                       
Starting  >>> opengv_catkin                                                     
Finished  <<< glog_catkin                                       [ 0.1 seconds ] 
Starting  >>> eigen_checks                                                      
Finished  <<< dbow2_catkin                                      [ 0.1 seconds ] 
Starting  >>> kimera_multi_lcd                                                  
________________________________________________________________________________
Errors     << kimera_multi_lcd:cmake /home/user/kimera_ws/logs/kimera_multi_lcd/build.cmake.001.log
CMake Error: The source "/home/user/kimera_ws/src/kimera_multi_lcd/CMakeLists.txt" does not match the source "/home/user/kimera_ws/src/Kimera-Multi-LCD/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
cd /home/user/kimera_ws/build/kimera_multi_lcd; catkin build --get-env kimera_multi_lcd | catkin env -si  /usr/bin/cmake /home/user/kimera_ws/src/kimera_multi_lcd --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/user/kimera_ws/devel/.private/kimera_multi_lcd -DCMAKE_INSTALL_PREFIX=/home/user/kimera_ws/install -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGTSAM_TANGENT_PREINTEGRATION=OFF -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DOPENGV_BUILD_WITH_MARCH_NATIVE=OFF; cd -

................................................................................
Failed     << kimera_multi_lcd:cmake                            [ Exited with code 1 ]
Failed    <<< kimera_multi_lcd                                  [ 0.1 seconds ] 
Abandoned <<< mesh_tools                                        [ Unrelated job failed ]
Abandoned <<< minkindr                                          [ Unrelated job failed ]
Abandoned <<< minkindr_conversions                              [ Unrelated job failed ]
Abandoned <<< minkindr_python                                   [ Unrelated job failed ]
Abandoned <<< kimera_vio                                        [ Unrelated job failed ]
Abandoned <<< kimera_distributed                                [ Unrelated job failed ]
Abandoned <<< kimera_vio_ros                                    [ Unrelated job failed ]
Abandoned <<< voxblox                                           [ Unrelated job failed ]
Abandoned <<< kimera_semantics                                  [ Unrelated job failed ]
Abandoned <<< kimera_pgmo                                       [ Unrelated job failed ]
Abandoned <<< voxblox_rviz_plugin                               [ Unrelated job failed ]
Abandoned <<< voxblox_ros                                       [ Unrelated job failed ]
Abandoned <<< kimera_semantics_ros                              [ Unrelated job failed ]
Finished  <<< dpgo_ros                                          [ 0.7 seconds ] 
Finished  <<< eigen_checks                                      [ 1.8 seconds ] 
________________________________________________________________________________
Errors     << rviz_map_plugin:make /home/user/kimera_ws/logs/rviz_map_plugin/build.make.001.log
In file included from /home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/src/ClusterLabelTool.cpp:49:
/home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
   57 | #include <CL/cl2.hpp>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/build.make:102: CMakeFiles/rviz_map_plugin.dir/src/ClusterLabelTool.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/include/ClusterLabelPanel.hpp:56,
                 from /home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/src/ClusterLabelPanel.cpp:49:
/home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
   57 | #include <CL/cl2.hpp>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/build.make:89: CMakeFiles/rviz_map_plugin.dir/src/ClusterLabelPanel.cpp.o] Error 1
In file included from /home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/include/ClusterLabelPanel.hpp:56,
                 from /home/user/kimera_ws/build/rviz_map_plugin/rviz_map_plugin_autogen/6YEA5652QU/moc_ClusterLabelPanel.cpp:9,
                 from /home/user/kimera_ws/build/rviz_map_plugin/rviz_map_plugin_autogen/mocs_compilation.cpp:3:
/home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
   57 | #include <CL/cl2.hpp>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/build.make:63: CMakeFiles/rviz_map_plugin.dir/rviz_map_plugin_autogen/mocs_compilation.cpp.o] Error 1
In file included from /home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/src/ClusterLabelDisplay.cpp:51:
/home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
   57 | #include <CL/cl2.hpp>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/build.make:76: CMakeFiles/rviz_map_plugin.dir/src/ClusterLabelDisplay.cpp.o] Error 1
In file included from /home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/src/MapDisplay.cpp:51:
/home/user/kimera_ws/src/mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
   57 | #include <CL/cl2.hpp>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/build.make:128: CMakeFiles/rviz_map_plugin.dir/src/MapDisplay.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:291: CMakeFiles/rviz_map_plugin.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/user/kimera_ws/build/rviz_map_plugin; catkin build --get-env rviz_map_plugin | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

................................................................................
Failed     << rviz_map_plugin:make                              [ Exited with code 2 ]
Failed    <<< rviz_map_plugin                                   [ 8.9 seconds ] 
Finished  <<< mesh_msgs_hdf5                                    [ 17.0 seconds ]
________________________________________________________________________________
Errors     << numpy_eigen:make /home/user/kimera_ws/logs/numpy_eigen/build.make.001.log
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_float.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<unsigned char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:63:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   63 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_float.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_float.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:74:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   74 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_float.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_float.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In function ‘const char* npyTypeToString(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:166:10: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
  166 |     case NPY_CHAR:
      |          ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_float.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<unsigned char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:63:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   63 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:74:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   74 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In function ‘const char* npyTypeToString(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:166:10: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
  166 |     case NPY_CHAR:
      |          ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/types/stack_t.h:23,
                 from /usr/include/signal.h:303,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/npy_interrupt.h:23,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:6,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp: In function ‘void init_module_libnumpy_eigen()’:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/__multiarray_api.h:1553:151: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
 1553 | #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NULL; } }
      |                                                                                                                                                       ^~~~
/home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:258:2: note: in expansion of macro ‘import_array’
  258 |  import_array();
      |  ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/numpy_eigen.dir/build.make:63: CMakeFiles/numpy_eigen.dir/src/autogen_module/numpy_eigen_export_module.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_double.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<unsigned char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:63:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   63 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_double.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_double.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:74:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   74 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_double.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_double.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In function ‘const char* npyTypeToString(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:166:10: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
  166 |     case NPY_CHAR:
      |          ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_double.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<unsigned char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:63:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   63 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:74:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   74 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In function ‘const char* npyTypeToString(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:166:10: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
  166 |     case NPY_CHAR:
      |          ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_uchar.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<unsigned char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:63:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   63 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_uchar.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_uchar.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:74:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   74 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_uchar.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_uchar.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In function ‘const char* npyTypeToString(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:166:10: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
  166 |     case NPY_CHAR:
      |          ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_uchar.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
make[1]: *** [CMakeFiles/Makefile2:422: CMakeFiles/numpy_eigen.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/user/kimera_ws/build/numpy_eigen; catkin build --get-env numpy_eigen | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

................................................................................
Failed     << numpy_eigen:make                                  [ Exited with code 2 ]
Failed    <<< numpy_eigen                                       [ 38.9 seconds ]
Finished  <<< kimera_rpgo                                       [ 53.7 seconds ]
________________________________________________________________________________
Warnings   << opengv_catkin:make /home/user/kimera_ws/logs/opengv_catkin/build.make.000.log
Cloning into 'opengv_src'...
Already on 'master'
Submodule 'python/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'python/pybind11'
Cloning into '/home/user/kimera_ws/build/opengv_catkin/opengv_src-prefix/src/opengv_src/python/pybind11'...
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'python/pybind11/tools/clang'
Cloning into '/home/user/kimera_ws/build/opengv_catkin/opengv_src-prefix/src/opengv_src/python/pybind11/tools/clang'...
make[3]: warning: -j8 forced in submake: resetting jobserver mode.
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
cd /home/user/kimera_ws/build/opengv_catkin; catkin build --get-env opengv_catkin | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

................................................................................
Finished  <<< opengv_catkin                                     [ 1 minute and 7.8 seconds ]
[build] Summary: 29 of 45 packages succeeded.                                   
[build]   Ignored:   None.                                                      
[build]   Warnings:  1 packages succeeded with warnings.                        
[build]   Abandoned: 13 packages were abandoned.                                
[build]   Failed:    3 packages failed.      
```

**Comment by sandilyasg** [comment]
**Potential solutions for solving the incompatibility issue between PCL and VTK:**

1. Try installing an older version of VTK that is compatible with the version of PCL you have installed. For example, if you have PCL 1.8, try installing VTK 6.3 instead of the latest VTK.
2. Build PCL from source instead of using the Debian packages. This will allow you to link against the desired VTK version.
3. Use the system versions of PCL and VTK rather than the ROS versions. Doing `sudo apt install libpcl-dev libvtk6-dev` may install compatible versions.
4. Build both PCL and VTK from source, configuring and compiling them together. This gives you full control over the versions and compatibility.
Building from source while specifying compatible versions is usually the most robust approach.

I also notice you are experiencing an error with the `rviz_map_plugin` package, specifically "fatal error: CL/cl2.hpp: No such file or directory
   57 | #include <CL/cl2.hpp>
      |          ^~~~~~~~~~~~
compilation terminated."

This is happening because your `/usr/include/CL` directory does not include the header file `cl2.hpp`. This is an issue in ubuntu that you have OpenCL C headers but not C++. A solution to this is to install the `opencl-clhpp-headers` package using `sudo apt install opencl-clhpp-headers`.

**Comment by zippyzoo77** [comment]
Thanks for the reply!
I did the last thing you have suggested there, so hopefully the cl2 stuff should be fixed now. 

I was looking for the compatible versions of PCL and VTK, and what other versions of VTK would work with PCL, and PCL depends on libvtk7-dev, which is on the machine already. I couldn't find any more on the versions, so I was going to try to make it with the cl2 fix and see what changed, and now I have only one package that comes up with an error, and one that fails because of that, and it looks like it's a different error now. I'm still working on figuring out to fix it, but I figured I would put up the error message here to see if you had any thoughts on how to fix this one. 

```
_______________________________________________________________________________
Errors     << numpy_eigen:make /home/user/kimera_ws/logs/numpy_eigen/build.make.001.log
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<unsigned char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:63:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   63 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:74:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   74 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In function ‘const char* npyTypeToString(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:166:10: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
  166 |     case NPY_CHAR:
      |          ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/import_long.cpp:4:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<unsigned char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:63:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   63 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In static member function ‘static bool TypeToNumPy<char>::canConvert(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:74:61: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
   74 |     return type == NPY_UBYTE || type == NPY_BYTE || type == NPY_CHAR;
      |                                                             ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:30,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp: In function ‘const char* npyTypeToString(int)’:
/home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/type_traits.hpp:166:10: warning: ‘NPY_CHAR’ is deprecated: Use NPY_STRING [-Wdeprecated-declarations]
  166 |     case NPY_CHAR:
      |          ^~~~~~~~
In file included from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:84:21: note: declared here
   84 |                     NPY_CHAR NPY_ATTR_DEPRECATE("Use NPY_STRING"),
      |                     ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/types/stack_t.h:23,
                 from /usr/include/signal.h:303,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/npy_interrupt.h:23,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:6,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp: In function ‘void init_module_libnumpy_eigen()’:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/__multiarray_api.h:1553:151: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
 1553 | #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NULL; } }
      |                                                                                                                                                       ^~~~
/home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:258:2: note: in expansion of macro ‘import_array’
  258 |  import_array();
      |  ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/numpy_eigen.dir/build.make:63: CMakeFiles/numpy_eigen.dir/src/autogen_module/numpy_eigen_export_module.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:422: CMakeFiles/numpy_eigen.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/user/kimera_ws/build/numpy_eigen; catkin build --get-env numpy_eigen | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

...............................................................................
Failed     << numpy_eigen:make                                  [ Exited with code 2 ]
Failed    <<< numpy_eigen                                       [ 21.8 seconds ]
Abandoned <<< minkindr_python                                   [ Depends on failed job numpy_eigen ]
```

**Comment by sandilyasg** [comment]
@zippyzoo77 Looks like the `cl2.hpp` error was solved. Here's how I think you could fix the deprecation warnings and subsequent error related to NumPy's `NPY_CHAR` type. `NPY_CHAR` has been deprecated in favor of `NPY_STRING`.
The key error is happening in `numpy/__multiarray_api.h` on this line:
`#define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NULL; } }`

The return `NULL` statement inside the macro is causing an issue because the surrounding function `init_module_libnumpy_eigen()` returns `void`.

Try upgrading NumPy to the latest version to see if the deprecation warnings go away. Since you are running Python3.8, the latest NumPy version is 1.24 according to [NumPy documentation](https://endoflife.date/numpy).

**Comment by zippyzoo77** [comment]
I updated from numpy version 1.24.2 to 1.24.4, but I'm still seeing the error and warnings from numpy-eigen.

**Comment by sandilyasg** [comment]
@zippyzoo77 I found the [ethz-asl/numpy_eigen](https://github.com/ethz-asl/numpy_eigen) repo issues something related:
[Get rid of deprecated NPY_CHAR warning #8](https://github.com/ethz-asl/numpy_eigen/pull/8) can you try disabling the warning?

Do you have multiple Python3 versions installed? You might have to use `pip3.8 install numpy==1.24.4` specifically.

**Comment by zippyzoo77** [comment]
I only have 3.8 and 2.7, but all the python stuff is set up to use the 3.8 only. 

That did get rid of the depreciation warnings, but the import_array() error is still present. 

```
Errors     << numpy_eigen:make /home/user/kimera_ws/logs/numpy_eigen/build.make.002.log
In file included from /usr/include/x86_64-linux-gnu/bits/types/stack_t.h:23,
                 from /usr/include/signal.h:303,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/npy_interrupt.h:23,
                 from /home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:6,
                 from /home/user/kimera_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:28,
                 from /home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp: In function ‘void init_module_libnumpy_eigen()’:
/home/user/.local/lib/python3.8/site-packages/numpy/core/include/numpy/__multiarray_api.h:1553:151: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
 1553 | #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NULL; } }
      |                                                                                                                                                       ^~~~
/home/user/kimera_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:258:2: note: in expansion of macro ‘import_array’
  258 |  import_array();
      |  ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/numpy_eigen.dir/build.make:63: CMakeFiles/numpy_eigen.dir/src/autogen_module/numpy_eigen_export_module.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:422: CMakeFiles/numpy_eigen.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/user/kimera_ws/build/numpy_eigen; catkin build --get-env numpy_eigen | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -


```

**Comment by zippyzoo77** [comment]
So I fixed it so it compiles by going into the file with the error and removing the NULL that was causing the error (similar to how the depreciation warnings were solved), but I don't know what else I have that relies on numpy that might end up with errors because of that... But it builds now so I guess we'll see.

**Comment by sandilyasg** [comment]
@zippyzoo77 I was thinking of suggesting this, but was unsure if any other packages would break due to changes to the package source code. Removing the "`return NULL`" statement should be fine though because I see that the function return type is `void`. It could also be a good idea to put a print statement using` std::cout` (and not `return`) for use with other packages

**Comment by zippyzoo77** [comment]
I'm not familiar enough with c++ to know what std::cout does, how would that work instead of the return statement? I left the return part there, I only removed the NULL.

So it was `#define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NULL; } }` originally. 

But I changed it to `#define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return; } }`. 

Are you suggesting `#define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); std::cout; } }` instead?

**Comment by sandilyasg** [comment]
Here is how you can print a warning instead of returning null:
`#define import_array() { if (_import_array() < 0) { PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); std::cout << "WARN: REMOVED NULL RETURN" << std::endl; } }`
Please view the example usage of `std::cout` [here](https://en.cppreference.com/w/cpp/io/cout).
